print("Добро пожаловать в ветеринарную клинику")
print ('Введите вид питомца:')
typeofanimal=input()
print ('Введите возраст питомца:')
age=input()
print ('Введите кличку питомца:')
nickname=input()
print("Кличка питомца:", nickname)
print ('Это', typeofanimal, "по кличке", nickname+".", "Его возраст:"+age + " год(а)" )
